version: '3'

services:
  minio:
    image: minio/minio:latest
    ports:
      - ${RUNNER_MINIO_PORT}:9000
    environment:
      MINIO_ACCESS_KEY: ${RUNNER_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${RUNNER_MINIO_SECRET_KEY}
    container_name: RUNNER_MINIO
    volumes:
      - /tmp/tweb/minio/data:/data
    command: ["server", "/data"]
  runner:
    image: registry.cn-hangzhou.aliyuncs.com/tradingai/runner:latest
    imagePullPolicy: always
    container_name: runner_client
    environment:
      TUSHARE_TOKEN: ${TUSHARE_TOKEN}
      TUSHARE_API: https://api.tushare.pro
      RUNNER_MINIO_ACCESS_KEY: ${RUNNER_MINIO_ACCESS_KEY}
      RUNNER_MINIO_SECRET_KEY: ${RUNNER_MINIO_SECRET_KEY}
      RUNNER_MINIO_HOST: ${RUNNER_MINIO_HOST}
      RUNNER_MINIO_PORT: ${RUNNER_MINIO_PORT}
      RUNNER_MINIO_SECURE: ${RUNNER_MINIO_SECURE}
      TWEB_CROS_ALLOW_ORIGINS: http://localhost:3030
      HEARTBEAT_SECONDS: ${HEARTBEAT_SECONDS}
      JOB_LOG_DIR: ${JOB_LOG_DIR}
      JOB_SHELL_DIR: ${JOB_SHELL_DIR}
    restart: always
