name: Docker

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run test in docker container
      run: docker-compose -f docker-compose.yml up --exit-code-from bazel bazel
      env:
        TWEB_POSTGRES_PORT: 5432
        TWEB_MINIO_PORT: 9000
        TWEB_PORT: 8888
        HEARTBEAT_SECONDS: 20

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: docker build
      run: make build_prod_image

    - name: docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: docker push-logout
      run: |
        docker push tradingai/runner:latest
        docker logout
    - name: ali docker login
      run:  echo "${{ secrets.ALI_DOCKER_PASSWORD }}" | docker login -u ${{ secrets.ALI_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin

    - name: ali tag
      run: docker tag tradingai/runner:latest registry.cn-hangzhou.aliyuncs.com/tradingai/runner:latest

    - name: ali docker push-logout
      run: |
        docker push registry.cn-hangzhou.aliyuncs.com/tradingai/runner:latest
        docker logout registry.cn-hangzhou.aliyuncs.com
