name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run tests in docker container
      env:
        BAZEL_USER_ROOT: /home/runner/BAZEL_USER_ROOT
        OUTPUT_DIR: /home/runner/OUTPUT_DIR
        TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        RUNNER_MINIO_ACCESS_KEY: ${{ secrets.RUNNER_MINIO_ACCESS_KEY }}
        RUNNER_MINIO_SECRET_KEY: ${{ secrets.RUNNER_MINIO_SECRET_KEY }}
        RUNNER_MINIO_HOST: ${{ secrets.RUNNER_MINIO_HOST }}
        RUNNER_MINIO_PORT: ${{ secrets.RUNNER_MINIO_PORT }}
        RUNNER_MINIO_SECURE: ${{ secrets.RUNNER_MINIO_SECURE }}
        HEARTBEAT_SECONDS: ${{ secrets.HEARTBEAT_SECONDS }}
        RUNNER_DATA_DIR: $${{ secrets.RUNNER_DATA_DIR }}
    volumes:
      - $${{ secrets.RUNNER_DATA_DIR }}:$${{ secrets.RUNNER_DATA_DIR }}:rw

      run: docker-compose up --exit-code-from test test
